/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package io.evacchi.github;

import io.github.evacchi.*;

dialect  "mvel"

// my_last(X,[X]).
// my_last(X,[_|L]) :- my_last(X,L).
rule "last0"
when
   $q: Query($L: query)
   $l : Last(list.tail == null)
then
    retract($l)
    insert(new Result(new Last($l.getList().getHead(), $q.getQuery().getList())))
    System.out.println("last is " + $l.getList().getHead());
end

rule "last1"
when
    $matched: Last($value: value, $list: list, list.tail != null)
then
    last = new Last($value, $list.getTail());
    retract($matched)
    insert(last)
    System.out.println("insert: "+last);
end

rule "query_last"
when
    Query($L: query)
then
    insert($L)
end
