/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package io.evacchi.github;

import io.github.evacchi.*;

dialect  "mvel"

//my_last(X,[X]).
//my_last(X,[H|T]) :- my_last(X,T).
query last(Object x, List l)
   ( x := Object() from l.head and
          List.Nil() from l.tail )
   or
  ( tail := List() from l.tail and
    ?last(x, tail;) )
end


//last_but_one(X,[X,_]).
//last_but_one(X,[_,Y|Ys]) :- last_but_one(X,[Y|Ys]).
query last_but_one(Object x, List l)
   (  x  := Object()   from l.head  and
      lt := List()     from l.tail  and
            Object()   from lt.head and
            List.Nil() from lt.tail )
   or
  (  t := List()   from l.tail and
          Object() from t.head and
          List()   from t.tail and
    ?last_but_one(x, t;) )
end
